import React from 'react';
import logo from './logo.svg';
import './App.css';
import Markov from "./Markov"
var text = `Donald John Trump (born June 14, 1946) is the 45th and current president of the United States. Before entering politics, he was a businessman and television personality.
Trump was born and raised in the New York City borough of Queens, and received a bachelor's degree in economics from the Wharton School. He took charge of his family's real-estate business in 1971, renamed it The Trump Organization, and expanded its operations from Queens and Brooklyn into Manhattan. The company built or renovated skyscrapers, hotels, casinos, and golf courses. Trump later started various side ventures, mostly by licensing his name. He owned the Miss Universe and Miss USA beauty pageants from 1996 to 2015, and produced and hosted The Apprentice, a reality television show, from 2003 to 2015. Forbes estimates his net worth to be $3.1 billion.

Trump entered the 2016 presidential race as a Republican and defeated 16 other candidates in the primaries. His political positions have been described as populist, protectionist, and nationalist. Despite being disfavored in most forecasts, he was elected in a surprise victory over Democratic nominee Hillary Clinton, although he lost the popular vote.He became the oldest first-term U.S. president, and the first without prior military or government service. His election and policies have sparked numerous protests. Trump has made many false or misleading statements during his campaign and presidency. The statements have been documented by fact-checkers, and the media have widely described the phenomenon as unprecedented in American politics. Many of his comments and actions have also been characterized as racially charged or racist.

During his presidency, Trump ordered a travel ban on citizens from several Muslim-majority countries, citing security concerns; after legal challenges, the Supreme Court upheld the policy's third revision. He enacted a tax-cut package for individuals and businesses, rescinding the individual health insurance mandate. He appointed Neil Gorsuch and Brett Kavanaugh to the Supreme Court. In foreign policy, Trump has pursued an America First agenda, withdrawing the U.S. from the Trans-Pacific Partnership trade negotiations, the Paris Agreement on climate change, and the Iran nuclear deal, eventually increasing tensions with the country. He recognized Jerusalem as the capital of Israel, imposed import tariffs triggering a trade war with China, and attempted negotiations with North Korea toward their denuclearization.

A special counsel investigation led by Robert Mueller found that Trump and his campaign welcomed and encouraged Russian foreign interference in the 2016 presidential election under the belief that it would be politically advantageous, but did not find sufficient evidence to press charges of criminal conspiracy or coordination with Russia. Mueller also investigated Trump for obstruction of justice, and his report neither indicted nor exonerated Trump on that score.

A 2019 House impeachment inquiry found that Trump solicited foreign interference in the 2020 U.S. presidential election from Ukraine to help his re-election bid, and then obstructed the inquiry itself. The inquiry reported that he withheld military aid and a White House invitation in order to influence Ukraine to publicly announce investigations into his political rivals. Trump was impeached by the House of Representatives on December 18, 2019, for abuse of power and obstruction of Congress. He is the third impeached U.S. president in history. Donald John Trump was born on June 14, 1946, at the Jamaica Hospital in the borough of Queens, New York City.[3][4] His father was Frederick Christ Trump, a Bronx-born real estate developer, whose own parents were German immigrants. His mother was Scottish-born housewife and socialite Mary Anne MacLeod Trump.[5] Trump grew up in the Jamaica Estates neighborhood of Queens, and attended the Kew-Forest School from kindergarten through seventh grade.[6][7] At age 13, he was enrolled in the New York Military Academy, a private boarding school.[8] In 1964, Trump enrolled at Fordham University.[9][10] Two years later he transferred to the Wharton School of the University of Pennsylvania.[10][11] While at Wharton, he worked at the family business, Elizabeth Trump & Son,[12] graduating in May 1968 with a B.S. in economics.[10][13][14] Profiles of Trump published in The New York Times in 1973 and 1976 erroneously reported that he had graduated first in his class at Wharton. However, he had never made the school's honor roll.[15] In 2015 Trump's lawyer Michael Cohen threatened Fordham University and the New York Military Academy with legal action if they released Trump's academic records.[16][17]

While in college, Trump obtained four student draft deferments.[18][19] In 1966, he was deemed fit for military service based upon a medical examination, and in July 1968 a local draft board classified him as eligible to serve.[20] In October 1968, he was medically deferred and classified 1-Y (unqualified for duty except in the case of a national emergency).[21] Trump said in 2015 that the medical deferment was due to a bone spur in a foot, though he could not remember which foot had been afflicted; his presidential campaign stated that the spurs were in both heels, a minor issue expected to be temporary.[21] In 1972, he was reclassified 4-F, which permanently disqualified him from service.[22][23] Trump's father, Fred, was born in 1905 in the Bronx. He started working with his mother in real estate when he was 15. Their company, "E. Trump & Son", founded in 1923,[24] was active in the New York boroughs of Queens and Brooklyn, building and selling thousands of houses, barracks, and apartments.[25] In spite of his German ancestry, Fred claimed to be Swedish amid the anti-German sentiment sparked by World War II;[26][27] Trump repeated this claim until the 1990s.[27][28] Trump's mother Mary Anne MacLeod was born in Scotland.[29] Fred and Mary were married in 1936 and raised their family in Queens.[29][30] Trump grew up with three elder siblings – Maryanne, Fred Jr., and Elizabeth – and younger brother Robert.[31]


Trump is sworn in as president by Chief Justice John Roberts on January 20, 2017: Trump, his wife Melania, and his children Donald Jr., Barron, Ivanka, Eric, and Tiffany.
In 1977, Trump married Czech model Ivana Zelníčková.[32][33] They have three children, Donald Jr. (born 1977), Ivanka (born 1981), and Eric (born 1984), and ten grandchildren.[34] Ivana became a naturalized United States citizen in 1988.[35] The couple divorced in 1992, following Trump's affair with actress Marla Maples.[36] Maples and Trump married in 1993[37][38] and had one daughter, Tiffany (born 1993).[39] They were divorced in 1999,[40] and Tiffany was raised by Marla in California.[41] In 2005, Trump married Slovenian model Melania Knauss.[42] They have one son, Barron (born 2006).[43] Melania gained U.S. citizenship in 2006.[44] Trump is a Presbyterian.[45] As a child, he attended the First Presbyterian Church in Jamaica, Queens, where he had his confirmation.[46] In the 1970s, his parents joined the Marble Collegiate Church in Manhattan,[47] part of the Reformed Church.[48] The pastor at Marble, Norman Vincent Peale,[46] ministered to Trump's family and mentored him until Peale's death in 1993.[49][47]

Trump says he is "not sure" whether he ever asked God for forgiveness: "If I do something wrong, I just try and make it right. I don't bring God into that picture." He tries to take Holy Communion as often as possible because it makes him "feel cleansed".[50] While campaigning, Trump referred to The Art of the Deal as his second favorite book saying, "Nothing beats the Bible."[51]

Trump has associations with a number of Christian spiritual leaders, including Florida pastor Paula White, who has been called his "closest spiritual confidant".[52] In 2015, he released a list of religious advisers, which included James Dobson, Jerry Falwell Jr., Ralph Reed, Michele Bachmann, and Robert Jeffress.[53][54] Trump abstains from alcohol, a reaction to his older brother Fred Trump Jr.'s alcoholism and early death,[55] and says he has never smoked cigarettes or cannabis.[56] He likes fast food.[57] He has said he prefers three to four hours of sleep per night.[58] He has called golfing his "primary form of exercise",[59] although he usually does not walk the course.[60][61] He considers exercise a waste of energy, because he believes the body is "like a battery, with a finite amount of energy".[62][63]

In December 2015, Harold Bornstein, who had been Trump's personal physician since 1980, wrote in a letter that he would "be the healthiest individual ever elected to the presidency".[64] In May 2018, Bornstein said Trump himself had dictated the contents of the letter,[65] and that Trump's representatives had taken away his medical records in February 2017.[66][67]

In January 2018, White House physician Ronny Jackson said Trump was in excellent health and that his cardiac assessment revealed no issues,[68] although his weight and cholesterol level were higher than recommended.[69] Several outside cardiologists commented that Trump's 2018 LDL cholesterol level of 143 did not indicate excellent health.[70] In February 2019, after a new examination, White House physician Sean Conley said Trump was in "very good health overall", although he was clinically obese.[71] His 2019 coronary CT calcium scan score indicates he suffers from coronary artery disease, which is common for white men at his age.[72] In 1982, Trump was listed on the initial Forbes list of wealthy individuals as having a share of his family's estimated $200 million net worth. His financial losses in the 1980s caused him to be dropped from the list between 1990 and 1995.[73] In its 2019 billionaires ranking, Forbes estimated Trump's net worth at $3.1 billion[a] (715th in the world, 259th in the U.S.)[76] making him one of the richest politicians in American history and the first billionaire American president.[76] During the three years since Trump announced his presidential run in 2015, Forbes estimated his net worth declined 31% and his ranking fell 138 spots.[77] When he filed mandatory financial disclosure forms with the Federal Elections Commission (FEC) in July 2015, Trump claimed a net worth of about $10 billion;[78] however FEC figures cannot corroborate this estimate because they only show each of his largest buildings as being worth over $50 million, yielding total assets worth more than $1.4 billion and debt over $265 million.[79] Trump stated in a 2007 deposition, "My net worth fluctuates, and it goes up and down with markets and with attitudes and with feelings, even my own feelings."[80] Journalist Jonathan Greenberg reported in April 2018 that Trump, using a pseudonym "John Barron", called him in 1984 to falsely assert that he owned "in excess of ninety percent" of the Trump family's business, in an effort to secure a higher ranking on the Forbes 400 list of wealthy Americans. Greenberg also wrote that Forbes had vastly overestimated Trump's wealth and wrongly included him on the Forbes 400 rankings of 1982, 1983, and 1984.[81]

Trump has often said he began his career with "a small loan of one million dollars" from his father, and that he had to pay it back with interest.[82] In October 2018, The New York Times reported that Trump "was a millionaire by age 8", borrowed at least $60 million from his father, largely failed to reimburse him, and had received $413 million (adjusted for inflation) from his father's business empire over his lifetime.[83][84] According to the report, Trump and his family committed tax fraud, which a lawyer for Trump denied. The tax department of New York says it is "vigorously pursuing all appropriate avenues of investigation" into it.[85][86] Analyses by The Economist and The Washington Post have concluded that Trump's investments underperformed the stock market.[87][88] Forbes estimated in October 2018 that the value of Trump's personal brand licensing business had declined by 88% since 2015, to $3 million.[89]

Trump's tax returns from 1985 to 1994 show net losses totaling $1.17 billion over the ten-year period, in contrast to his claims about his financial health and business abilities. The New York Times reported that "year after year, Mr. Trump appears to have lost more money than nearly any other individual American taxpayer", and Trump's "core business losses in 1990 and 1991 – more than $250 million each year – were more than double those of the nearest taxpayers in the I.R.S. information for those years". In 1995 his reported losses were $915.7 million.[90][91] Trump began his career in 1968 at his father Fred's real estate development company, E. Trump & Son, which owned middle-class rental housing in New York City's outer boroughs.[92][93] He assisted his father in the attempted turnaround of the troubled Swifton Village apartment complex in Cincinnati, Ohio, which the elder Trump had bought at foreclosure in 1964.[94][95] In 1971, when his father promoted him to president of the family company, he renamed it The Trump Organization.[96][95] Trump attracted public attention in 1978 with the launch of his family's first Manhattan venture, the renovation of the derelict Commodore Hotel, adjacent to Grand Central Terminal. The financing was facilitated by a $400 million city property tax abatement arranged by Fred Trump,[97] who also joined Hyatt in guaranteeing $70 million in bank construction financing.[98][99] The hotel reopened in 1980 as the Grand Hyatt Hotel,[100] and that same year, Trump obtained rights to develop Trump Tower, a mixed-use skyscraper in Midtown Manhattan.[101][102] That building was formerly Trump's primary residence and now houses the headquarters of the Trump Organization.[103][104]

In 1988, Trump acquired the Plaza Hotel in Manhattan with a loan of $425 million from a consortium of banks. Two years later, the hotel filed for bankruptcy protection, and a reorganization plan was approved in 1992.[105] In 1995, Trump lost the hotel to Citibank and investors from Singapore and Saudi Arabia, who assumed $300 million of the debt.[106][107]

In 1996, Trump acquired a vacant 71-story skyscraper at 40 Wall Street. After an extensive renovation, the high-rise was renamed the Trump Building.[108] In the early 1990s, Trump won the right to develop a 70-acre (28 ha) tract in the Lincoln Square neighborhood near the Hudson River. Struggling with debt from other ventures in 1994, Trump sold most of his interest in the project to Asian investors who were able to finance completion of the project, Riverside South. Trump temporarily retained a partial stake in an adjacent site along with other investors.[109] In 1985, Trump acquired the Mar-a-Lago estate in Palm Beach, Florida.[110][111][112] Trump used a wing of the estate as a home, while converting the remainder into a private club with an initiation fee and annual dues.[113] The initiation fee was $100,000 until 2016; it was doubled to $200,000 in January 2017.[114] On September 27, 2019, Trump declared Mar-a-Lago his primary residence.[115][116] In 1984, Trump opened Harrah's at Trump Plaza hotel and casino in Atlantic City, New Jersey with financing from the Holiday Corporation, who also managed the operation. Gambling had been legalized there in 1977 in an effort to revitalize the once-popular seaside destination.[117] Soon after it opened the casino was renamed "Trump Plaza", but the property's poor financial results worsened tensions between Holiday and Trump, who paid Holiday $70 million in May 1986 to take sole control of the property.[118][119][120] Earlier, Trump had also acquired a partially completed building in Atlantic City from the Hilton Corporation for $320 million. Upon its completion in 1985, that hotel and casino was called Trump Castle. Trump's then-wife Ivana managed it until 1988.[121][122] Trump acquired a third casino in Atlantic City, the Taj Mahal, in 1988 in a highly leveraged transaction.[123] It was financed with $675 million in junk bonds and completed at a cost of $1.1 billion, opening in April 1990.[124][125][126] The project went bankrupt the following year,[127] and the reorganization left Trump with only half his initial ownership stake and required him to pledge personal guarantees of future performance.[128] Facing "enormous debt", he gave up control of his money-losing airline, Trump Shuttle, and sold his 282-foot (86 m) mega yacht, the Trump Princess, which had been indefinitely docked in Atlantic City while leased to his casinos for use by wealthy gamblers.[129][130][131]

In 1995, Trump founded Trump Hotels & Casino Resorts (THCR), which assumed ownership of Trump Plaza, Trump Castle, and the Trump Casino in Gary, Indiana.[132] THCR purchased the Taj Mahal in 1996 and underwent successive bankruptcies in 2004, 2009, and 2014, leaving Trump with only ten percent ownership.[133] He remained chairman of THCR until 2009.[134] As of December 2016, the Trump Organization owns or operates 18 golf course and golf resorts in the United States and abroad.[135] According to Trump's FEC personal financial disclosure, his 2015 golf and resort revenue amounted to $382 million,[136][137] while his three European golf courses did not show a profit.[138]

Trump began acquiring and constructing golf courses in 1999; his first property was the Trump International Golf Club, West Palm Beach in Florida.[139] By 2007, he owned four courses around the U.S.[139] Following the financial crisis of 2007–2008, he began purchasing existing golf courses and re-designing them.[140] His use of these courses during his presidency was controversial. Despite frequently criticizing his predecessor Barack Obama for his numerous golf outings, Trump golfed eleven times during his first eight weeks in office.[141] He visited one of his golf resorts on 187 of his first 848 days in office, 22 percent of the time.[142] After the Trump Organization's financial losses in the early 1990s, it refocused its business on branding and licensing the Trump name for building projects that are owned and operated by other people and companies.[143] In the late 2000s and early 2010s, it expanded this branding and management business to hotel towers owned by various developers around the world. These included projects in Chicago, Las Vegas, Washington D.C., Panama City, Toronto, and Vancouver. There are also Trump-branded buildings in Dubai, Honolulu, Istanbul, Manila, Mumbai, and Indonesia.[144]

The Trump name has also been licensed for various consumer products and services, including the short-lived Cadillac Trump Series,[dubious – discuss][145][146] foodstuffs, apparel, adult learning courses, and home furnishings.[147][148] According to an analysis by The Washington Post, there are more than fifty licensing or management deals involving Trump's name, which have generated at least $59 million in yearly revenue for his companies.[149] By 2018 only two consumer goods companies continued to license his name.[148] As of April 2018, Trump and his businesses had been involved in more than 4,000 state and federal legal actions, according to a running tally by USA Today.[150] As of 2016, he or one of his companies had been the plaintiff in 1,900 cases and the defendant in 1,450. With Trump or his company as plaintiff, more than half the cases have been against gamblers at his casinos who had failed to pay off their debts. With Trump or his company as a defendant, the most common type of case involved personal injury cases at his hotels. In cases where there was a clear resolution, Trump's side won 451 times and lost 38.[151][152]

Trump has never filed for personal bankruptcy.[153] His hotel and casino businesses have been declared bankrupt six times between 1991 and 2009 in order to re-negotiate debt with banks and owners of stock and bonds.[154][155] Because the businesses used Chapter 11 bankruptcy, they were allowed to operate while negotiations proceeded. Trump was quoted by Newsweek in 2011 saying, "I do play with the bankruptcy laws – they're very good for me" as a tool for trimming debt.[156][157] The six bankruptcies were the result of over-leveraged hotel and casino businesses in Atlantic City and New York: Trump Taj Mahal (1991), Trump Plaza Hotel and Casino (1992), Plaza Hotel (1992), Trump Castle Hotel and Casino (1992), Trump Hotels and Casino Resorts (2004), and Trump Entertainment Resorts (2009).[158][159]

During the 1980s, more than 70 banks had lent Trump $4 billion,[160] but in the aftermath of his corporate bankruptcies of the early 1990s, most major banks declined to lend to him, with a notable exception of Deutsche Bank.[161]

In April 2019, the House Oversight Committee issued subpoenas seeking financial details from Trump's banks, Deutsche Bank and Capital One, and his accounting firm, Mazars USA. In response, Trump sued the banks, Mazars, and committee chairman Elijah Cummings to prevent the disclosures.[162][163] In May, DC District Court judge Amit Mehta ruled that Mazars must comply with the subpoena,[164] and judge Edgardo Ramos of the Southern District Court of New York ruled that the banks must also comply.[165][166] Trump's attorneys appealed the rulings,[167] arguing that Congress was attempting to usurp the "exercise of law-enforcement authority that the Constitution reserves to the executive branch".[168][169] After taking over control of the Trump Organization in 1971, Trump expanded its real estate operations and ventured into other business activities. The company eventually became the umbrella organization for several hundred individual business ventures and partnerships.[170][171]

In September 1983, Trump purchased the New Jersey Generals – an American football team that played in the United States Football League. After the 1985 season, the league folded largely due to Trump's strategy of moving games to a fall schedule where they competed with the NFL for audience, and trying to force a merger with the NFL by bringing an antitrust lawsuit against the organization.[172][173]

Trump's businesses have hosted several boxing matches at the Atlantic City Convention Hall adjacent to and promoted as taking place at the Trump Plaza in Atlantic City, including Mike Tyson's 1988 heavyweight championship fight against Michael Spinks.[174][175] In 1989 and 1990, Trump lent his name to the Tour de Trump cycling stage race, which was an attempt to create an American equivalent of European races such as the Tour de France or the Giro d'Italia.[176]

Trump purchased significant blocks of shares in various public companies during the late 1980s, as Wall Street saw a wave of corporate acquisitions known as leveraged buyouts. In some cases, these acquisitions were hostile takeovers conducted by so-called corporate raiders. Some raiders purchased a stake in a public company with the stated but feigned intent of acquiring it, then pressured management to repurchase the stake at a profitable premium for the raider — a practice known as greenmail. Some observers believed Trump was engaged in such practices, though he denied it. Analysis conducted by The New York Times found that Trump made millions of dollars in these stock transactions, but "lost most, if not all, of those gains after investors stopped taking his takeover talk seriously."[177][178][179]

In 1988, Trump founded Trump Shuttle, purchasing 21 planes and landing rights at three airports in New York City, Boston, and the Washington, D.C., area, from the defunct Eastern Air Lines, costing $380 million financed from 22 banks. The airline offered charter services in addition to scheduled shuttle flights, and was eventually sold to USAir Group in 1992 after failing to operate at a profit.[180] From 1996 to 2015, Trump owned part of or all the Miss Universe pageants, including Miss USA and Miss Teen USA.[181][182] Due to disagreements with CBS about scheduling, he took both pageants to NBC in 2002.[183][184] In 2007, Trump received a star on the Hollywood Walk of Fame for his work as producer of Miss Universe.[185] In September 2015, Trump bought NBC's share of the Miss Universe Organization, and sold the entire company to the William Morris talent agency.[186] n 2004, Trump co-founded a company called Trump University that sold real estate training courses priced at between $1,500 and $35,000.[187][188][189] After New York State authorities twice notified the company that its use of the word "university" violated state law, its name was changed to the "Trump Entrepreneurial Institute" in 2010.[190]

In 2013, the State of New York filed a $40 million civil suit against Trump University; the suit alleged that the company made false statements and defrauded consumers.[190][191] In addition, two class-action civil lawsuits were filed in federal court; they named Trump personally as well as his companies. Internal documents of the company revealed that employees were instructed to use a hard-sell approach, and former employees said in depositions that Trump University had defrauded or lied to its students.[192][193][194][195][196] Shortly after he won the presidency, Trump agreed to a settlement of all three pending cases and agreed to pay a total of $25 million.[197] New York Attorney General Eric Schneiderman called the settlement and payment "a stunning reversal by Donald Trump and a major victory for the over 6,000 victims of his fraudulent university".[198] Trump denied any wrongdoing.[199][200] The Donald J. Trump Foundation was a U.S.-based private foundation[201] established in 1988 for the initial purpose of giving away proceeds from the book Trump: The Art of the Deal.[202][203] The foundation's funds have mostly come from donors other than Trump, who has not given personally to the charity since 2008.[204]

The foundation's tax returns show that it has given to health care and sports-related charities, as well as conservative groups.[205] In 2009, for example, the foundation gave $926,750 to about forty groups, with the biggest donations going to the Arnold Palmer Medical Center Foundation ($100,000), the NewYork–Presbyterian Hospital ($125,000), the Police Athletic League ($156,000), and the Clinton Foundation ($100,000).[206][207] From 2004 to 2014, the top donors to the foundation were Vince and Linda McMahon of WWE, who donated $5 million to the foundation after Trump appeared at WrestleMania in 2007.[204]

In 2016, The Washington Post reported that the charity had committed several potential legal and ethical violations, including alleged self-dealing and possible tax evasion.[208] Also in 2016, the New York State Attorney General's office notified the Trump Foundation that the foundation appeared to be in violation of New York laws regarding charities, ordering it to immediately cease its fundraising activities in New York.[209][210][211] A Trump spokesman called the Attorney General's investigation a "partisan hit job".[209] In response to mounting complaints, Trump's team announced in late December 2016 that the Trump Foundation would be dissolved to remove "even the appearance of any conflict with [his] role as President".[212] According to an IRS filing in November 2017, the foundation intended to shut down and distribute its assets (about $970,000) to other charities. However, the New York Attorney General's office had to complete their ongoing investigation before the foundation could legally shut down,[213] and in June 2018 they filed a civil suit against the foundation for $2.8 million in restitution and additional penalties.[214] The suit names Trump himself as well as his adult children Donald Jr., Eric, and Ivanka.[215]

In December 2018, the foundation agreed to cease operation and disburse all its assets. Attorney General Barbara Underwood, who oversaw the investigation and lawsuit, said the investigation uncovered a "shocking pattern of illegality".[216][217] Months later, a New York state judge ordered Trump to pay $2 million to a group of charities for "breaching his fiduciary duty to properly oversee the foundation that bears his name". The Foundation characterized the penalty as a "contribution", stating it was "pleased to donate an additional $2 million" to "worthy organizations". Trump acknowledged that a January 2016 fundraiser for veterans he organized had actually been a campaign event and the $2.8 million in raised funds were placed under the full control of his campaign.[218][219] Before being inaugurated as president, Trump moved his businesses into a revocable trust run by his eldest sons and a business associate.[220][221] According to ethics experts, as long as Trump continues to profit from his businesses, the measures taken by Trump do not help to avoid conflicts of interest.[222] Because Trump would have knowledge of how his administration's policies would affect his businesses, ethics experts recommend that Trump sell off his businesses.[221] While Trump said his organization would eschew "new foreign deals", the Trump Organization has since pursued expansions of its operations in Dubai, Scotland, and the Dominican Republic.[222]

Multiple lawsuits have been filed alleging that Trump is violating the Emoluments Clause of the United States Constitution, which forbids presidents from taking money from foreign governments, due to his business interests; they argue that these interests allow foreign governments to influence him.[222][223] Previous presidents in the modern era have either divested their holdings or put them in blind trusts,[220] and he is the first president to be sued over the emoluments clause.[223] According to The Guardian, "NBC News recently calculated that representatives of at least 22 foreign governments – including some facing charges of corruption or human rights abuses such as Saudi Arabia, Malaysia, Turkey and the Philippines – seem to have spent funds at Trump properties while he has been president."[224] On October 21, 2019, Trump mocked the Emoluments Clause as "phony".[225]

In 2015, Trump said he "makes a lot of money with" the Saudis and that "they pay me millions and hundreds of millions."[226] And at a political rally, Trump said about Saudi Arabia: "They buy apartments from me. They spend $40 million, $50 million. Am I supposed to dislike them? I like them very much."[227]

In December 2015, Trump said in a radio interview that he had a "conflict of interest" in dealing with Turkey and Turkish president Tayyip Erdoğan because of his Trump Towers Istanbul, saying "I have a little conflict of interest because I have a major, major building in Istanbul and it's a tremendously successful job ... It's called Trump Towers – two towers instead of one ... I've gotten to know Turkey very well".[228][229]`
//text = "Trump A Trump B Trump C Trump A"
function App() {
  var m = new Markov(text,2);
  return (
    <div className="App">
      <h1>{m.generateForMe()}</h1>
    </div>
  );
}

export default App;
